### ISSUE TITLE
Excel export does not contain tweet text

### ISSUE THREAD

**Issue by peterk** [gwu-libraries/sfm-ui#936] opened 2018-06-29 08:35 UTC
Running SFM 1.12 and noticed that Excel exports no longer contain the text of a tweet. The text column in the exported Excel file is empty.

<img width="477" alt="image" src="https://user-images.githubusercontent.com/19284/42082266-d4561230-7b87-11e8-9b1a-2a346ed63222.png">

Exporting the same collection to json gives the full data so I am sure it has been collected properly.

**Comment by justinlittman** [comment] 2018-07-05 14:19
Duplicate of #935.

@peterk - to fix:
1. `docker-compose stop twitterrestexporter twitterstreamexporter`
2. Change the version of the Twitter rest exporter and Twitter stream exporter to 1.12.1 in your docker-compose.yml.
3. `docker-compose up -d`.

Please re-open if this doesn't correct the problem. Sorry about that!

**Closed by justinlittman** 2018-07-05 14:19 UTC
Labels: bug
