### ISSUE TITLE
Error in weibo export README

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#610] opened 2016-12-20 22:19 UTC
Steps to reproduce:
1.  Create a weibo collection and perform a harvest.
2. Create an export of the collection.
3. Look at the README.txt.

Expected result:
The images sizes are listed in the README.txt.

Actual result:
```
Image sizes: <ul></ul>
```

**Comment by Tanych** [comment] 2016-12-27 15:17
@justinlittman 
The default option for weibo image size `list` is NULL, so when the [json_text](https://github.com/gwu-libraries/sfm-ui/blob/98f714ffd64591747ba82596cc5e2aa8a521b57b/sfm/ui/templatetags/ui_extras.py#L87) try to analysis the json option in text view, it would return `<ul></ul>`. It's the similar problem with `flickr`.
If the option is as follows:
```json
"options": {
        "web_resources": false, 
        "incremental": true, 
        "image_sizes": [
            "Thumbnail", 
            "Medium"
        ]
    }

```
The `json_text` will return:
```
Harvest options:
Web resources: No
Incremental: Yes
Image sizes: <ul><li>Thumbnail</li><li>Medium</li></ul>
```

**Comment by Tanych** [comment] 2016-12-27 15:32
I think it's not a bug. It's a friendly use case. If we change the list view to `["Thumbnail", "Medium"]` in `readme.txt`, other issues for `html` template to show will occur.  The details is [here](https://github.com/gwu-libraries/sfm-ui/blob/98f714ffd64591747ba82596cc5e2aa8a521b57b/sfm/ui/templatetags/ui_extras.py#L78).

**Comment by justinlittman** [comment] 2017-01-11 19:34
@Tanych Can you take a look at https://github.com/gwu-libraries/sfm-ui/tree/t610-exporter_readme2?  I think it may be a simpler solution.

**Comment by Tanych** [comment] 2017-01-11 22:02
@justinlittman Yeap, it's simpler. I intended to consider that `json_text` will be used in another place which needs the html format `<li></li>`. If it won't happen, we can make it much simpler like this.

**Comment by justinlittman** [comment] 2017-01-12 11:39
OK.  Either review and merge my code or update your version.

**Comment by Tanych** [comment] 2017-01-12 15:05
@justinlittman have merged your code and tested!

**Closed** 2017-01-18 13:20 UTC
Labels: bug, pull request, trivial effort level
