### ISSUE TITLE
Bulk seeds one fails indicating all fail 

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#376] opened 2016-07-15 13:21 UTC
Adding `n seeds` using bulk seeds, if one of them fails when process, it will influence all the process. All the other seeds won't process in the right way. Also, users can't know which seed has the problem.

**Comment by kerchner** [comment] 2016-07-15 13:26
Closing - duplicate of #346

**Closed by kerchner** 2016-07-15 13:26 UTC
Labels: duplicate
