### ISSUE TITLE
Prevent duplication (case-insensitive) within the same bulk add list

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#650] opened 2017-01-20 17:09 UTC
Bulk add seems to allow duplicate seeds within the set (might be only if they're different cases).  Not sure whether #489 only added checking against seeds already in the collection (vs. in the same bulk list being added).

See http://ec2-54-144-198-169.compute-1.amazonaws.com/ui/collections/8/  where I was able to add both
`wolfCreekNFH` and
`WolfCreekNFH`
in the same bulk add.

**Comment by justinlittman** [comment] 2017-01-23 13:58
Duplicate of #640.

**Closed by justinlittman** 2017-01-23 13:58 UTC
Labels: bug, duplicate, low effort level
