### ISSUE TITLE
Export xlsx format with errors

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#475] opened 2016-10-10 15:10 UTC
* To xlsx
```python
Traceback (most recent call last):
  File "weibo_exporter.py", line 83, in <module>
    WeiboExporter.main(WeiboExporter, QUEUE, [TIME_LINE_ROUTING_KEY])
  File "/usr/local/lib/python2.7/site-packages/sfmutils/exporter.py", line 236, in main
    exporter.run()
  File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 177, in run
    for _ in self.consume(limit=None):  # pragma: no cover
  File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 199, in consume
    conn.drain_events(timeout=safety_interval)
  File "/usr/local/lib/python2.7/site-packages/librabbitmq/__init__.py", line 220, in drain_events
    self._basic_recv(timeout)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 598, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 564, in receive
    [callback(body, message) for callback in callbacks]
  File "/usr/local/lib/python2.7/site-packages/sfmutils/consumer.py", line 121, in _callback
    self.on_message()
  File "/usr/local/lib/python2.7/site-packages/sfmutils/exporter.py", line 106, in on_message
    export_formats[export_format][1](table, filepath)
  File "/usr/local/lib/python2.7/site-packages/petl/io/xlsx.py", line 74, in toxlsx
    wb = openpyxl.Workbook(optimized_write=True, encoding=encoding)
TypeError: __init__() got an unexpected keyword argument 'optimized_write'
```

**Comment by Tanych** [comment] 2016-10-10 19:57
I have rebuilt the master branches in two different machine, both have the same issue. Not just for weibo-exporter, all exporter is the same.

**Comment by Tanych** [comment] 2016-10-10 20:31
A little tricky thing is that it works when I use the docker image `gwul/sfm-weibo-exporter:1.1.0`. However, the error occurs when I use docker image `gwul/sfm-weibo-exporter:master`. Actually, there are no differences between the source code in tag **1.1.0** and branch **master**.

**Comment by Tanych** [comment] 2016-10-10 21:06
## Solution
Exporting **xlsx** most depends on the library **openpyxl**.
When I dig into the build detail for the 1.1.0 and master, the diff of [docker hub](https://hub.docker.com/r/gwul/sfm-weibo-exporter/builds/bay8zbynmgtvmeq9tmtdrjp/) logs are as following:
* 1.1.0
```bash
Collecting openpyxl>=2.3.3 (from sfmutils->-r requirements/release.txt (line 2))
  Downloading openpyxl-2.3.5.tar.gz (141kB)
Collecting iso8601>=0.1.11 (from sfmutils->-r requirements/release.txt (line 2))
  Downloading iso8601-0.1.11-py2.py3-none-any.whl
Collecting jdcal (from openpyxl>=2.3.3->sfmutils->-r requirements/release.txt (line 2))
  Downloading jdcal-1.2.tar.gz
Collecting et-xmlfile (from openpyxl>=2.3.3->sfmutils->-r requirements/release.txt (line 2))
  Downloading et_xmlfile-1.0.1.tar.gz
```
openpyxl is **2.3.5**.

* master 
```bash
Collecting openpyxl>=2.3.3 (from sfmutils->-r requirements/release.txt (line 2))
  Downloading openpyxl-2.4.0.tar.gz (153kB)
Collecting iso8601>=0.1.11 (from sfmutils->-r requirements/release.txt (line 2))
  Downloading iso8601-0.1.11-py2.py3-none-any.whl
Collecting jdcal (from openpyxl>=2.3.3->sfmutils->-r requirements/release.txt (line 2))
  Downloading jdcal-1.2.tar.gz
Collecting et-xmlfile (from openpyxl>=2.3.3->sfmutils->-r requirements/release.txt (line 2))
  Downloading et_xmlfile-1.0.1.tar.gz
```
openpyxl is **2.4.0** release at October 06, 2016.
The newest build will pull the lastest **openpyxl** , it might have some issues with the version. 
We need to make sure the instance for openpyxl is 2.3.5 or 2.3.3.

**Comment by justinlittman** [comment] 2016-10-11 14:51
This was also reported by Sara Day Thompson (DPC). I committed to having this fixed by Monday for a presentation she is giving.

**Comment by Tanych** [comment] 2016-10-11 14:55
@justinlittman  do we need to skip the **2.4.0**, as the [pip requirement](https://pip.readthedocs.io/en/stable/reference/pip_install/#requirements-file-format) says: we can skip the openpyxl version like this:
`pip install "openpyxl >=2.3.3,<2.4.0"`

In **requirement.txt**:
`openpyxl >=2.3.3,<2.4.0`

**Comment by Tanych** [comment] 2016-10-11 15:15
The **openpyxl**  only responses to the first error, Do I need to make a separate issue for the second one?

**Comment by justinlittman** [comment] 2016-10-11 15:35
So I think the problem is that common.txt in sfm-master has gotten out of sync with common.txt in each of the harvester repos.

For example, https://github.com/gwu-libraries/sfm-utils/blob/master/requirements/common.txt has 33 entries, while https://github.com/gwu-libraries/sfm-twitter-harvester/blob/master/requirements/common.txt has 30.

It appears that one of the missing requirements is openpyxl.

**Comment by Tanych** [comment] 2016-10-11 15:46
The openpyxl will on the sfm-utils, all the harvesters, exporters docker images  are based on the sfm-utils  requirements. If we go to the harvesters building file:
```bash
RUN pip install -r requirements/common.txt -r requirements/release.txt
```
**common.txt** is the requirements for harvesters and exporters .
**release.txt** comes from sfm-utils and warproxy

Logs:
```bash
Collecting openpyxl>=2.3.3 (from sfmutils->-r requirements/release.txt (line 2))
  Downloading openpyxl-2.4.0.tar.gz (153kB)
```

**Comment by justinlittman** [comment] 2016-10-11 15:55
So here's what happens:
1. pip install -r common.txt.  This is the common.txt that exists within
the individual harvester project.  This is missing opepyxl, so it won't get
installed.
2. pip install -r release.txt or master.txt.  This installs sfm-utils,
which installs dependencies from sfm-util's setup.py.  This setup.py
includes openpyxl>=2.3.3, which installs openpyxl 2.4.0.

The solution is two-fold:
1.  Add openpyxl (and all of the other missing dependencies) to the
common.txt in each of the harvester projects.
2. Set the version correctly in sfm-util's setup.py to openpyxl >=2.3.3 and
<2.4.0.

**Comment by Tanych** [comment] 2016-10-11 15:58
I think the second one might be more simple to do since all the harvesters,exporters and sfm-ui are all based on the sfm-utils.

**Comment by justinlittman** [comment] 2016-10-11 17:14
It is simpler, but we want to freeze all of the dependencies.  setup.py
doesn't allow that.  So we should do both.

**Closed** 2016-10-13 17:10 UTC
Labels: bug, pull request
