### ISSUE TITLE
Keep track of WARCs loaded into ELK

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#335] opened 2016-06-15 11:17 UTC
For monitoring/admining/troubleshooting ELK, it would be helpful to have a log of what WARCs have been loaded into ELK.  It might also be useful for preventing duplicate loads.

**Comment by kerchner** [comment] 2016-07-05 18:27
Duplicate of #322.

**Closed by kerchner** 2016-07-05 18:27 UTC
Labels: duplicate
