### ISSUE TITLE
Connect Weibo/Twitter Account crash with duplicate credential

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#807] opened 2017-05-01 23:45 UTC
### Replicate
* Active `connect twitter account` button.
* Click connect the twitter account and sign in 
* Credential  create successfully
* Re-Click the connect twitter account button again
* Error happens.
### Expect results
notice with `credentials already exist!`

### Actural errors
![connect twitter](https://cloud.githubusercontent.com/assets/3956411/25598926/2505a22a-2ea6-11e7-8bf3-fd819b70c329.png)

### Reason
The simply duplicate credential check won't allow the duplicate credential. Need reconsider to implement to check the duplicate credential with update view.
Original issue https://github.com/gwu-libraries/sfm-ui/issues/573

**Comment by kerchner** [comment] 2017-05-08 14:48
May be duplicate of #664

**Comment by Tanych** [comment] 2017-05-11 20:26
### For test
#### Test 1
* create a `credential_1` with value {`access_token`:1234}
* create a `credential_2` with value {`access_token`:1234}
* Expect result: **Not accept!**

#### Test 2
* create a `credential_1` with value {`access_token`:1234}
* create a `credential_2` with value {`access_token`:12345}
* update `credential_1` with value {`access_token`:12345}
* Expect result: **Not accept!**

#### Test 3
* create a `credential_1` with value {`access_token`:1234}
* update `credential_1` and keep token value {`access_token`:1234}, but change name to `credential_2`
* Expect result: **Accept!**

#### Test 4
* Connect `Twitter/Weibo` APP to add a credential, suppose value is {`access_token`:1234}
* Click connect once again!
* Expect result: **no server error and notificate  with credential exist!**

**Comment by lwrubel** [comment] 2017-06-19 17:10
Closed with #822.

**Closed by lwrubel** 2017-06-19 17:10 UTC
Labels: bug, low effort level, pull request
